import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs } from "firebase/firestore";
import fs from "fs";
import path from "path";

const firebaseConfig = {
  apiKey: "AIzaSyCjsOHkhs3LlvlL6UBWK96EA86-sicbeq0",
  authDomain: "ayush946portfolio.firebaseapp.com",
  projectId: "ayush946portfolio",
  storageBucket: "ayush946portfolio.firebasestorage.app",
  messagingSenderId: "364535937831",
  appId: "1:364535937831:web:8344c2e9d1a81ddf704702",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

async function syncFallbackData() {
  console.log("Downloading latest public data from Firestore...");

  try {
    const projectsSnap = await getDocs(collection(db, "projects"));
    const projects = projectsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const experiencesSnap = await getDocs(collection(db, "experiences"));
    const experiences = experiencesSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const skillsSnap = await getDocs(collection(db, "skills"));
    const skills = skillsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    const certsSnap = await getDocs(collection(db, "certificates"));
    const certificates = certsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

    // Generate TypeScript file content
    const fileContent = `// AUTO-GENERATED FALLBACK DATA
// This file is generated by scripts/syncFallbackData.ts
// It acts as a fail-safe cache if the database is unreachable.
// No sensitive keys are stored here.

export const fallbackProjects = ${JSON.stringify(projects, null, 2)};

export const fallbackExperiences = ${JSON.stringify(experiences, null, 2)};

export const fallbackSkills = ${JSON.stringify(skills, null, 2)};

export const fallbackCertificates = ${JSON.stringify(certificates, null, 2)};
`;

    const filePath = path.join(process.cwd(), "src", "data", "fallbackData.ts");
    fs.writeFileSync(filePath, fileContent, "utf8");

    console.log("✅ Successfully synchronized fallbackData.ts with the latest database contents!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Sync failed:", error);
    process.exit(1);
  }
}

syncFallbackData();
